### ISSUE TITLE
整一个没有 translate3d 之类的幺蛾子的版本

### ISSUE THREAD

**Issue by Artoria2e5** [vbup-osc/new-pekobutton#14]
不说这个到底有没有设计上的意义，translate3d 嵌套是浏览器 bug 大苗床。

Chrome 86.0.4209.2，Windows，不 hover 有些字就显示不出：
![image](https://user-images.githubusercontent.com/6459309/88782898-b511f380-d1c0-11ea-855f-1a7dbeecb449.png)

Safari Version 13.1.1 (15609.2.9.1.2)，macOS，hover 了东西就会消失：
<img width="1920" alt="Screen Shot 2020-07-29 at 17 28 23" src="https://user-images.githubusercontent.com/6459309/88783219-18038a80-d1c1-11ea-8d6d-7d0dc92afb0e.png">

另外到处乱动真的很丑，像是哪个兔子亲自指挥部署的一样。按钮按下去颜色变一下就够了，还不用写那么多种 `@media`。

**Comment by fz6m** [comment]
我这里没有复现你说的情况，可能是数据字体没有加载出来，请确保你的网络环境哈
